// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from SsoDev.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace ssodev {

    class SsoDev {
    public:
        virtual ~SsoDev() {}

        static std::shared_ptr<SsoDev> create(const std::string & address, const std::string & ca);

        virtual std::string get_public_key() = 0;

        virtual int32_t do_register(const std::string & username, const std::string & password, const std::string & mac, const std::string & public_key) = 0;

        virtual std::string do_login(const std::string & username, const std::string & password, const std::string & mac, const std::string & public_key) = 0;

        virtual int32_t do_keep_touch(const std::string & username, const std::string & mac, const std::string & ticket) = 0;

        virtual int32_t do_logout(const std::string & username, const std::string & ticket) = 0;

        virtual std::string test(const std::string & t) = 0;
    };

}  // namespace ssodev